jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Set up Docker private registry
      run: 'docker run -d -p 5000:5000 --restart=always --name registry registry:2

        docker run -d -p 5001:5000 --restart=always --name secure_registry -v "$(pwd)"/src/functTest/resources/auth:/auth:rw
        -e "REGISTRY_AUTH=htpasswd" -e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm"
        -e "REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd" registry:2

        '
    - continue-on-error: true
      name: Set up Gradle
      uses: gradle/gradle-build-action@v2
    - continue-on-error: true
      name: Compilation
      run: ./gradlew classes
    - continue-on-error: true
      name: Validate plugins
      run: ./gradlew validatePlugins
    - continue-on-error: true
      name: Unit tests
      run: ./gradlew test
    - continue-on-error: true
      name: Integration tests
      run: ./gradlew integrationTest
    - continue-on-error: true
      env:
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
        HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
      name: Functional tests
      run: ./gradlew functionalTest
    - continue-on-error: true
      name: Documentation tests
      run: ./gradlew docTest
    - continue-on-error: true
      name: Assemble artifacts
      run: ./gradlew assemble javadoc asciidoctorAllGuides
    - continue-on-error: true
      name: Upload binaries
      uses: actions/upload-artifact@v3
      with:
        name: gradle-docker-plugin-bin
        path: build/libs/*.jar
    - continue-on-error: true
      name: Upload Javadoc
      uses: actions/upload-artifact@v3
      with:
        name: gradle-docker-plugin-javadoc
        path: build/docs/javadoc/
    - continue-on-error: true
      name: Upload Guides
      uses: actions/upload-artifact@v3
      with:
        name: gradle-docker-plugin-guides
        path: 'build/docs/asciidocDevGuide/

          build/docs/asciidocUserGuide/

          '
    - continue-on-error: true
      if: startsWith(github.ref, 'refs/tags/')
      name: Release
      run: ./gradlew publishPlugins gitPublishPush -Pgradle.publish.key=${{ secrets.PLUGIN_PORTAL_KEY
        }} -Pgradle.publish.secret=${{ secrets.PLUGIN_PORTAL_SECRET }} -Dorg.ajoberstar.grgit.auth.username=${{
        secrets.GH_TOKEN }} -is
name: Build and Release [Linux]
on:
  repository_dispatch:
    types: trigger-ga___linux-build-release.yml
