jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Set up Gradle
      uses: gradle/gradle-build-action@v2
    - continue-on-error: true
      name: Compilation
      run: ./gradlew classes
    - continue-on-error: true
      name: Unit tests
      run: ./gradlew test
    - continue-on-error: true
      name: Integration tests
      run: ./gradlew integrationTest
    - continue-on-error: true
      name: Assemble artifacts
      run: ./gradlew assemble javadoc asciidoctorAllGuides
name: Build [Windows]
on:
  repository_dispatch:
    types: trigger-ga___windows-build.yml
